// Code generated by "stringer -type=ast_type,ast_modifier,file_type -output=parser_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NULL-0]
	_ = x[BLANK-1]
	_ = x[RAW-2]
	_ = x[NORMAL-3]
	_ = x[TOKEN-4]
	_ = x[IMPORT-5]
	_ = x[PARTIAL-6]
	_ = x[TEMPLATE-7]
	_ = x[SCOPE_UNSET-8]
	_ = x[DECL-9]
	_ = x[DECL_BLOCK-10]
	_ = x[DECL_TOKEN-11]
	_ = x[VAR-12]
	_ = x[VAR_ENUM-13]
	_ = x[VAR_ANON-14]
	_ = x[RES_FINDER-15]
	_ = x[BLOCK-16]
	_ = x[is_formatter-17]
	_ = x[ITALIC_OPEN-18]
	_ = x[ITALIC_CLOSE-19]
	_ = x[BOLD_OPEN-20]
	_ = x[BOLD_CLOSE-21]
	_ = x[BOLD_ITALIC_OPEN-22]
	_ = x[BOLD_ITALIC_CLOSE-23]
	_ = x[MARK_OPEN-24]
	_ = x[MARK_CLOSE-25]
	_ = x[STRIKE_OPEN-26]
	_ = x[STRIKE_CLOSE-27]
	_ = x[is_lexer-28]
	_ = x[WHITESPACE-29]
	_ = x[NEWLINE-30]
	_ = x[WORD-31]
	_ = x[IDENT-32]
	_ = x[EQUALS-33]
	_ = x[BRACE_OPEN-34]
	_ = x[BRACE_CLOSE-35]
	_ = x[BRACKET_OPEN-36]
	_ = x[BRACKET_CLOSE-37]
	_ = x[ANGLE_OPEN-38]
	_ = x[ANGLE_CLOSE-39]
	_ = x[is_non_word-40]
	_ = x[NON_WORD-41]
	_ = x[ESCAPE-42]
	_ = x[FORWARD_SLASH-43]
	_ = x[NUMBER-44]
	_ = x[STOP-45]
	_ = x[COLON-46]
	_ = x[ASTERISK-47]
	_ = x[AMPERSAND-48]
	_ = x[TILDE-49]
	_ = x[PLUS-50]
	_ = x[MULTIPLY-51]
	_ = x[PERCENT-52]
	_ = x[EOF-53]
}

const _ast_type_name = "NULLBLANKRAWNORMALTOKENIMPORTPARTIALTEMPLATESCOPE_UNSETDECLDECL_BLOCKDECL_TOKENVARVAR_ENUMVAR_ANONRES_FINDERBLOCKis_formatterITALIC_OPENITALIC_CLOSEBOLD_OPENBOLD_CLOSEBOLD_ITALIC_OPENBOLD_ITALIC_CLOSEMARK_OPENMARK_CLOSESTRIKE_OPENSTRIKE_CLOSEis_lexerWHITESPACENEWLINEWORDIDENTEQUALSBRACE_OPENBRACE_CLOSEBRACKET_OPENBRACKET_CLOSEANGLE_OPENANGLE_CLOSEis_non_wordNON_WORDESCAPEFORWARD_SLASHNUMBERSTOPCOLONASTERISKAMPERSANDTILDEPLUSMULTIPLYPERCENTEOF"

var _ast_type_index = [...]uint16{0, 4, 9, 12, 18, 23, 29, 36, 44, 55, 59, 69, 79, 82, 90, 98, 108, 113, 125, 136, 148, 157, 167, 183, 200, 209, 219, 230, 242, 250, 260, 267, 271, 276, 282, 292, 303, 315, 328, 338, 349, 360, 368, 374, 387, 393, 397, 402, 410, 419, 424, 428, 436, 443, 446}

func (i ast_type) String() string {
	if i >= ast_type(len(_ast_type_index)-1) {
		return "ast_type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ast_type_name[_ast_type_index[i]:_ast_type_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[SLUG-1]
	_ = x[UNIQUE_SLUG-2]
	_ = x[UPPER-3]
	_ = x[LOWER-4]
	_ = x[TITLE-5]
	_ = x[EXPAND-6]
	_ = x[EXPAND_ALL-7]
}

const _ast_modifier_name = "NONESLUGUNIQUE_SLUGUPPERLOWERTITLEEXPANDEXPAND_ALL"

var _ast_modifier_index = [...]uint8{0, 4, 8, 19, 24, 29, 34, 40, 50}

func (i ast_modifier) String() string {
	if i >= ast_modifier(len(_ast_modifier_index)-1) {
		return "ast_modifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ast_modifier_name[_ast_modifier_index[i]:_ast_modifier_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DIRECTORY-0]
	_ = x[ROOT-1]
	_ = x[is_image-2]
	_ = x[IMG_JPG-3]
	_ = x[IMG_PNG-4]
	_ = x[IMG_TIF-5]
	_ = x[IMG_WEB-6]
	_ = x[end_image-7]
	_ = x[is_page-8]
	_ = x[MARKUP-9]
	_ = x[MARKDOWN-10]
	_ = x[is_static-11]
	_ = x[HTML-12]
	_ = x[end_page-13]
	_ = x[STATIC-14]
	_ = x[JAVASCRIPT-15]
	_ = x[SCSS-16]
	_ = x[CSS-17]
	_ = x[end_static-18]
}

const _file_type_name = "DIRECTORYROOTis_imageIMG_JPGIMG_PNGIMG_TIFIMG_WEBend_imageis_pageMARKUPMARKDOWNis_staticHTMLend_pageSTATICJAVASCRIPTSCSSCSSend_static"

var _file_type_index = [...]uint8{0, 9, 13, 21, 28, 35, 42, 49, 58, 65, 71, 79, 88, 92, 100, 106, 116, 120, 123, 133}

func (i file_type) String() string {
	if i >= file_type(len(_file_type_index)-1) {
		return "file_type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _file_type_name[_file_type_index[i]:_file_type_index[i+1]]
}
