#!/bin/bash

set -e

# copy the version into the manual source as a template
version=$(grep 'const VERSION' source/*.go | awk -F"[ \"]+" '/VERSION/{print $4}')
echo -n "VERSION = $version" > manual/config/templates/version.x


# build the manual using Spindle
pushd manual > /dev/null
spindle.exe build
popd > /dev/null



# create data_manual.go by packing the rendered
# HTML into a switch of strings
target=source/data_manual.go

cat text/header_license.txt > $target
printf "

// this file was generated by tool/embed.sh: don't modify!

package main

func manual_content(arg string) string {
	switch arg {
" >> $target

for f in manual/public/*; do
	name=$(basename ${f%.html})
	name=${name/*_}

	if [ $name == "index" ]; then
		printf "\tdefault:\n\t\treturn \`" >> $target
	else
		printf "\tcase \"$name\":\n\t\treturn \`" >> $target
	fi

	echo -n "$(cat $f)" >> $target
	printf "\`\n" >> $target
done

printf "\t}\n}\n\n" >> $target



# include the help.txt text
data=$(fold -w 64 -s text/help.txt)
printf "const HELP_TEXT = \`\n$data\`" >> $target