# Normally if you wanted to achieve these top-level root URLs,
# you'd use "root" as the path mode and put the correct domain
# in so your canonical URLs could still be correct.  Here, I
# don't want to bother with canonical URLs and I also don't
# want to put all my files two levels down (_spindle/manual), so
# I'm using "absolute" mode — which includes the domain in
# every link — and then putting in a fake domain that cheats
# for me.  It's really just acting as a site-wide prefix.

# Public-facing sites shouldn't be built like this.
# Put your actual "https://domain.com/" in there.

domain = "/_spindle/manual/"

path_mode  = "absolute"
build_path = "public"

sitemap = false

[[inline]]
pattern  = '\[(.+?)\]\((.+?)\)'
template = '<a href="$2">$1</a>'

[[inline]]
pattern  = '`(.+?)`'
template = '<code>$1</code>'