/*
	Spindle
	A static site generator
	Copyright (C) 2022-2023 Harley Denham

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// this file was generated by tool/builtin_ids.go

package main

const (
	_DEFAULT          uint32 = 2470140894
	_BASE             uint32 = 537692064
	_STOP             uint32 = 722245873
	_INDEX            uint32 = 151693739
	_IT               uint32 = 1194886160
	_LAST             uint32 = 1675745305
	_IS_SERVER        uint32 = 3202569332
	_RELOAD_SCRIPT    uint32 = 3668506343
	_PAGE_PATH        uint32 = 3389556212
	_PAGE_URL         uint32 = 3862688697
	_PAGE_CANONICAL   uint32 = 1769793352
	_PAGE_PARENT      uint32 = 3048082238
	_IMPORT_PATH      uint32 = 3719848934
	_IMPORT_URL       uint32 = 4180644383
	_IMPORT_CANONICAL uint32 = 2934264558
	_TAGINATOR        uint32 = 296413604
	_TAGINATOR_ACTIVE uint32 = 1983695352
	_TAGINATOR_TAG    uint32 = 3373312024
	_TAGINATOR_ALL    uint32 = 3084771407
	_TAGINATOR_PARENT uint32 = 2722466740
)