/*
	Spindle
	A static site generator
	Copyright (C) 2022-2023 Harley Denham

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//go:build debug

// Code generated by "stringer -type=AST_Type,File_Type,Path_Type,Exec_Type,Modifier -output=_parser_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NULL-0]
	_ = x[BLANK-1]
	_ = x[RAW-2]
	_ = x[NORMAL-3]
	_ = x[TOKEN-4]
	_ = x[IMPORT-5]
	_ = x[PARTIAL-6]
	_ = x[TEMPLATE-7]
	_ = x[UNSET-8]
	_ = x[SCRIPT-9]
	_ = x[DECL-10]
	_ = x[DECL_BLOCK-11]
	_ = x[DECL_TOKEN-12]
	_ = x[DECL_REJECT-13]
	_ = x[VAR-14]
	_ = x[VAR_ENUM-15]
	_ = x[VAR_ANON-16]
	_ = x[CONTROL_FOR-17]
	_ = x[CONTROL_IF-18]
	_ = x[OP_AND-19]
	_ = x[OP_OR-20]
	_ = x[OP_NOT-21]
	_ = x[RES_FINDER-22]
	_ = x[BLOCK-23]
	_ = x[is_formatter-24]
	_ = x[ITALIC_OPEN-25]
	_ = x[ITALIC_CLOSE-26]
	_ = x[BOLD_OPEN-27]
	_ = x[BOLD_CLOSE-28]
	_ = x[BOLD_ITALIC_OPEN-29]
	_ = x[BOLD_ITALIC_CLOSE-30]
	_ = x[MARK_OPEN-31]
	_ = x[MARK_CLOSE-32]
	_ = x[STRIKE_OPEN-33]
	_ = x[STRIKE_CLOSE-34]
	_ = x[WHITESPACE-35]
	_ = x[is_lexer-36]
	_ = x[NEWLINE-37]
	_ = x[WORD-38]
	_ = x[IDENT-39]
	_ = x[BRACE_OPEN-40]
	_ = x[BRACE_CLOSE-41]
	_ = x[BRACKET_OPEN-42]
	_ = x[BRACKET_CLOSE-43]
	_ = x[ANGLE_OPEN-44]
	_ = x[ANGLE_CLOSE-45]
	_ = x[ESCAPE-46]
	_ = x[NUMBER-47]
	_ = x[FORWARD_SLASH-48]
	_ = x[MULTIPLY-49]
	_ = x[AMPERSAND-50]
	_ = x[COLON-51]
	_ = x[TILDE-52]
	_ = x[EOF-53]
	_ = x[DOLLAR-54]
	_ = x[is_non_word-55]
	_ = x[NON_WORD-56]
	_ = x[ASTERISK-57]
	_ = x[EQUALS-58]
	_ = x[BANG-59]
	_ = x[STOP-60]
	_ = x[PLUS-61]
	_ = x[PERCENT-62]
	_ = x[PIPE-63]
}

const _AST_Type_name = "NULLBLANKRAWNORMALTOKENIMPORTPARTIALTEMPLATEUNSETSCRIPTDECLDECL_BLOCKDECL_TOKENDECL_REJECTVARVAR_ENUMVAR_ANONCONTROL_FORCONTROL_IFOP_ANDOP_OROP_NOTRES_FINDERBLOCKis_formatterITALIC_OPENITALIC_CLOSEBOLD_OPENBOLD_CLOSEBOLD_ITALIC_OPENBOLD_ITALIC_CLOSEMARK_OPENMARK_CLOSESTRIKE_OPENSTRIKE_CLOSEWHITESPACEis_lexerNEWLINEWORDIDENTBRACE_OPENBRACE_CLOSEBRACKET_OPENBRACKET_CLOSEANGLE_OPENANGLE_CLOSEESCAPENUMBERFORWARD_SLASHMULTIPLYAMPERSANDCOLONTILDEEOFDOLLARis_non_wordNON_WORDASTERISKEQUALSBANGSTOPPLUSPERCENTPIPE"

var _AST_Type_index = [...]uint16{0, 4, 9, 12, 18, 23, 29, 36, 44, 49, 55, 59, 69, 79, 90, 93, 101, 109, 120, 130, 136, 141, 147, 157, 162, 174, 185, 197, 206, 216, 232, 249, 258, 268, 279, 291, 301, 309, 316, 320, 325, 335, 346, 358, 371, 381, 392, 398, 404, 417, 425, 434, 439, 444, 447, 453, 464, 472, 480, 486, 490, 494, 498, 505, 509}

func (i AST_Type) String() string {
	if i >= AST_Type(len(_AST_Type_index)-1) {
		return "AST_Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AST_Type_name[_AST_Type_index[i]:_AST_Type_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DIRECTORY-0]
	_ = x[ROOT-1]
	_ = x[is_image-2]
	_ = x[IMG_JPG-3]
	_ = x[IMG_PNG-4]
	_ = x[IMG_TIF-5]
	_ = x[IMG_WEB-6]
	_ = x[IMG_GIF-7]
	_ = x[end_image-8]
	_ = x[is_page-9]
	_ = x[MARKUP-10]
	_ = x[MARKDOWN-11]
	_ = x[is_static-12]
	_ = x[HTML-13]
	_ = x[end_page-14]
	_ = x[STATIC-15]
	_ = x[JAVASCRIPT-16]
	_ = x[SCSS-17]
	_ = x[CSS-18]
	_ = x[end_static-19]
}

const _File_Type_name = "DIRECTORYROOTis_imageIMG_JPGIMG_PNGIMG_TIFIMG_WEBIMG_GIFend_imageis_pageMARKUPMARKDOWNis_staticHTMLend_pageSTATICJAVASCRIPTSCSSCSSend_static"

var _File_Type_index = [...]uint8{0, 9, 13, 21, 28, 35, 42, 49, 56, 65, 72, 78, 86, 95, 99, 107, 113, 123, 127, 130, 140}

func (i File_Type) String() string {
	if i >= File_Type(len(_File_Type_index)-1) {
		return "File_Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _File_Type_name[_File_Type_index[i]:_File_Type_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_PATH_TYPE-0]
	_ = x[RELATIVE-1]
	_ = x[ABSOLUTE-2]
	_ = x[ROOTED-3]
}

const _Path_Type_name = "NO_PATH_TYPERELATIVEABSOLUTEROOTED"

var _Path_Type_index = [...]uint8{0, 12, 20, 28, 34}

func (i Path_Type) String() string {
	if i >= Path_Type(len(_Path_Type_index)-1) {
		return "Path_Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Path_Type_name[_Path_Type_index[i]:_Path_Type_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_NO_EXEC-0]
	_ = x[_LOCATOR-1]
	_ = x[_DATE-2]
}

const _Exec_Type_name = "_NO_EXEC_LOCATOR_DATE"

var _Exec_Type_index = [...]uint8{0, 8, 16, 21}

func (i Exec_Type) String() string {
	if i >= Exec_Type(len(_Exec_Type_index)-1) {
		return "Exec_Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Exec_Type_name[_Exec_Type_index[i]:_Exec_Type_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[SLUG-1]
	_ = x[UNIQUE_SLUG-2]
	_ = x[UPPER-3]
	_ = x[LOWER-4]
	_ = x[TITLE-5]
	_ = x[EXPAND-6]
	_ = x[EXPAND_ALL-7]
}

const _Modifier_name = "NONESLUGUNIQUE_SLUGUPPERLOWERTITLEEXPANDEXPAND_ALL"

var _Modifier_index = [...]uint8{0, 4, 8, 19, 24, 29, 34, 40, 50}

func (i Modifier) String() string {
	if i >= Modifier(len(_Modifier_index)-1) {
		return "Modifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Modifier_name[_Modifier_index[i]:_Modifier_index[i+1]]
}
